//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departmentDetail
    {
        public int deptId { get; set; }
        public string deptName { get; set; }
        public Nullable<int> numOfEmployees { get; set; }
    }
}
